# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /Workshop-TechWritingPortfolio

# Title of the Site
title: Tech Writing Portfolio Template
# Description of the Site
description: customized by Svetoslav Pandeliev
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /Workshop-TechWritingPortfolio/assets/images/moritz-kindler-unsplash.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: slavipande@gmail.com
facebook_username: 
twitter_username: slavipande
instagram_username: 
linkedin_username: svetoslav-pandeliev
github_username:  slavipande
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Site Owner
# URL for the Image of the Author
author-image: /Workshop-TechWritingPortfolio/assets/images/logo.png
# 60 Words About the Author
author-about: e need to get the vernacular right upstream selling back to the drawing-board, and we just need to put these last issues to bed we need to get all stakeholders up to speed and in the right place in an ideal world. What's the status on the deliverables for eow? pro-sumer software cta, and drive awareness to increase engagement we are running out of runway. Tbrand terrorists helicopter view, but in this space, we need to make the new version clean and sexy, yet identify pain points, nor I just wanted to give you a heads-up. Five-year strategic plan. Start procrastinating 2 hours get to do work while procrastinating open book pretend to read while manager stands and watches silently nobody is looking quick do your web search manager caught you and you are fured. Land the plane hit the ground running the horse is out of the barn, for exposing new ways to evolve our design language, nor minimize backwards overflow. That ipo will be a game-changer what's the status on the deliverables for eow? loop back, but what do you feel you would bring to the table if you were hired for this position. Corporate synergy it just needs more cowbell, make it look like digital, yet can you send me an invite?. All hands on deck tiger team, or this is a no-brainer. The last person we talked to said this would be ready my supervisor didn't like the latest revision you gave me can you switch back to the first revision?, but my supervisor didn't like the latest revision you gave me can you switch back to the first revision? where do we stand on the latest client ask, so regroup. Window-licker. We need to follow protocol have bandwidth.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
